module.exports = [
  "What do you mean?",
  "I'm not sure I understand",
  "Are you sure?",
  "why would you say that?",
  "What makes you feel that way?",
  "If you could go back, would you still feel that way?",
  "I think I'm understanding you, continue",
  "Can you elaborate",
  "You’re making total sense.",
  "I understand how you feel",
  "I know why you would say that...", 
  "You're in a tough spot, I'm sorry...", 
  "I can feel the pain you're experiencing",
  "The world needs to just stop when you feel this way.", 
  "Look, I understand and I'm on your side", 
  "That hurts me to hear that", 
  "I support your position", 
  "I totally agree", 
  "You are feeling so trapped", 
  "You are feeling so helpless", 
  "No, that makes perfect sense", 
  "No wonder you're upset...", 
  "I think I'd feel the same way if I were in your position", 
  "I wish I could free you from this", 
  "That sounds infuriating", 
  "Well, I agree with most of what you're saying", 
  "That sounds a little frightening", 
  "Tell me what you see as your choices here",
  "I can see how important this is to you.",
  "I understand this can be frustrating", 
  "I know this process can be annoying...", 
  "I'd like to help, if possible", 
  "okay...can you tell me what's been going on?", 
]