module.exports = [
  'thank you, god loves you, thanks from god',
  'we appreciate your worship, god and i',
  'the Lord\'s work never ends, grace unto you',
  'God is in control.',
  'What\'s God doing in your life?',
  'We\'re in the end times.',
  'Do you know where you’re going to go after you die?',
  'What would you say if you stood before God after you die?',
  'Have you found Jesus?',
  'It takes more faith to be an atheist than a Christian.',
  'Have you made your peace with God?', 
  'What blessings has the Lord given to you?',
  'Don\'t forget to count your blessings!',
  'With God all things are possible.',
  'Remember, Faith is to believe what we do not see, and the reward of this faith is to see what we believe.',
  'Jesus never pussyfooted',
  'Life can only be understood backwards, but it must be lived forwards.',
  'As a Christian, youre not a citizen of this world trying to get to heaven; youre a citizen of heaven making your way through this world.',
  'God’s work done in God’s way will never lack God’s supplies',
  'God loves each of us as if there were only one of us',
  'God never said that the journey would be easy, but He did say that the arrival would be worthwhile',
  'God will meet you where you are in order to take you where He wants you to go.',
  'He is no fool who gives what he cannot keep, to gain what he cannot lose.',
  'Remember who you are. Don’t compromise for anyone, for any reason. You are a child of the Almighty God. Live that truth.',
  'There is no one who is insignificant in the purpose of God.',
  'Relying on God has to start all over everyday, as if nothing has yet been done.',
  'Your potential is the sum of all the possibilities God has for your life.',
  'Be faithful in small things because it is in them that your strength lies.',
  'Every Christian is either a missionary or an imposter.',
  'God has given believers the responsibility of spreading the gospel to all the world, and we need to do it!',
  'The way you store up treasure in heaven is by investing in getting people there.',
  'If you had the cure to cancer wouldn\'t you share it? You have the cure to death, SHARE IT!',
  'To be a soul winner is the happiest thin in this world.',
  'Any method of evangelism will work if God is in it.',
  'The mission of the Church is to seek and save them that are lost.',
  'And he said unto them, Go into all the world and proclaim the gospel to my creation.',
  'God proved his love on the Cross. When Christ hung, and bled, and died, it was God saying to the world, ‘I love you.',
  'It is the Holy Spirit\'s job to convict, God\'s job to judge and my job to love.',
  'I\'ve read the last page of the Bible, it\'s all going to turn out all right.',
  'People who hate God take it out on innocent people.',
  'I believe if you keep your faith, you keep your trust, you keep the right attitude, if you’re grateful, you’ll see God open up new doors.',
  'Life’s too short to spend it trying to keep others happy. You can’t please everyone. To fulfill your destiny, stay true to your heart.',
  'Nothing in life has happened to you. It’s happened for you. Everything has helped make you into who you are.',
  'God would not have put a dream in your heart if He had not already given you everything you need to fulfill it.',
  'If you have your health, if you have people in your life to love, you are blessed. Slow down and enjoy the simple things in life.',
  'Start believing today that things are going to change for the better. Your best days are still out in front of you.',
  'No matter what’s happening, choose to be happy. Don’t focus on what’s wrong. Thank God for the small things',
  'Don’t waste your energy trying to convince people to understand you. Your time is too valuable to try to prove yourself to people',
  'God will always bring the right people into your life, but you have to let the wrong people walk away.',
  'Don’t make excuses, don’t blame the past. The rest of your life can be the best of your life!',
  'There may be times when you just have to love people from a distance.',
  'Hard times may have held you down, but they will not last forever. When all is said and done, you will be better off than before.',
  'No matter how dark and gloomy it looks in your life right now, you will see the sun break forth.',
  'When the negative thoughts come it’s not enough to just not dwell on it. You’ve got to replace it with a positive thought.',
  'Friend, there’s no greater investment in life than in being a people builder. Relationships are more important than our accomplishments.',
  'Do all you can to make your dreams come true.',
  'Sometimes we look back and 10 years from now we think, ‘Boy, those were great old days.’ Well, you know, we’re living in the good old days.',
  'You were not created with an average, unrewarding, or unfulfilling life. God created you to leave your mark on this generation.',
  'Indeed, it is as important to learn how to receive a blessing as it is to be willing to give one.”',
  'You will never change what you tolerate.',
  'If we’re going to bring out the best in people, we, too, need to sow seeds of encouragement.',
  'We may get knocked down on the outside, but the key to living in victory is to learn how to get up on the inside.',
  'The question is not, ‘Do you have a problem?’ The question is, ‘Does the problem have you?',
  'Don’t just accept whatever comes your way. You were born to win; you were born for greatness; you were created to be a champion.',
  'Keep in mind, just because you don’t know the answer doesn’t mean that one does not exist. You simply haven’t discovered it yet.',
  'In difficult times, we’re not supposed to quit believing; we’re not supposed to quit growing.', 
  'Choose your friends with caution; plan your future with purpose, and frame your life with faith.',
  'Whatever our calling, regardless of our fears or anxieties, let us pray and then go and do.',
  'Courage, not compromise, brings the smile of God\'s approval',
  'Find someone who is having a hard time, or is ill, or lonely, and do something for him or her.',
  'In reality, we are all travelers - even explorers of mortality.',
  'The future is as bright as your faith.',
  'We may not only find faith in God in our sorrow. We may also become faithful to Him in times of calm.',
  'Faith and doubt cannot exist in the same mind at the same time, for one will dispel the other.',
  'The way to be with God in every season is to strive to be near Him every week and each day.',
  'We must develop the capacity to see men not as they are at present but as they may become.',
  'May I always be found \'on the Lord\'s errand.',
  'I testify that this work in which we\'re engaged is the Lord\'s work. I\'ve felt His sustaining influence.',
  'Have you no wish for others to be saved? Then you are not saved yourself.',
  'It\'s not our business to make the message acceptable, but to make it available.',
  'Faith is to rest, not in the best of God’s servants, but in his unchanging Word.',
  'The first duty of the gospel preacher is to declare God’s law and to show the nature of sin.',
  'Let’s quit fiddling with religion and do something to bring the world to Christ.',
  'God save us from living in comfort while sinners are sinking into hell.',
  'The Jesus that men want to see is not the Jesus they need to see.',
  'If you have no joy there’s a leak in your Christianity somewhere.',
  'Christ is either Lord of all, or he is not Lord at all.',
  'The scriptures are given not to increase our knowledge, but to change our lives.',
  'Joy is the gigantic secret of the Christian life.',
  'Out of 100 men, one will read the Bible, the other 99 will read the Christian.',
  'We have a God who delights in impossibilities.',
  'Prayer can never be in excess.',
  'Our love to God is measured by our everyday fellowship with others and the love it displays',
  'The remarkable thing is, we have a choice everyday regarding the attitude we will embrace for that day.',
  'Immerse yourself in the curriculum of grace.',
  'Consider what you owe to His immutability. Though you have changed a thousand times, He has not changed once',
  'Without a purpose, life is motion without meaning, activity without direction, and events without reason.',
  'When you read the Bible, read for quality not quantity',
  'No one can pray and worry at the same time.',
  'A man who wants to lead the orchestra must turn his back on the crowd',
  'God loves us too much to indulge our every whim',
]